version: "3"

services:
  clickhouse:
    container_name: clickhouse
    build:
      context: .
      args:
        CLICKHOUSE_DB: ${CLICKHOUSE_DB}
        CLICKHOUSE_USER: ${CLICKHOUSE_USER}
        CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
        CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    restart: always
    env_file:
      - .env
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native protocol
      - "9009:9009"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

volumes:
  clickhouse-data:
  clickhouse-logs:
